-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS AS a
LEFT JOIN ANIMAL_OUTS AS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE LIKE "%Intact%" and (b.SEX_UPON_OUTCOME LIKE "%Spayed%" OR b.SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY a.ANIMAL_ID